#!/bin/bash
# set -o errexit
# set -o nounset
# set -o pipefail
export OS_AUTH_URL={{DEP_0_SPEC_PROVIDER_0_SPEC_AUTH_KEYSTONEURL}}
export OS_TENANT_ID={{DEP_0_SPEC_PROVIDER_0_SPEC_AUTH_TENANTID}}
export OS_TENANT_NAME={{DEP_0_SPEC_PROVIDER_0_SPEC_AUTH_TENANTNAME}}
export OS_REGION_NAME={{DEP_0_SPEC_PROVIDER_0_SPEC_AUTH_REGIONNAME}}
if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi
