[requirements]
network={{ DEP_CONFIGURATION_0_SPEC_PLATFORM_0_SPEC_NETCOUNT | default("1") }}
subnet={{ DEP_CONFIGURATION_0_SPEC_PLATFORM_0_SPEC_SUBNETCOUNT | default("1") }}
router={{ DEP_CONFIGURATION_0_SPEC_PLATFORM_0_SPEC_ROUTERCOUNT | default("1") }}
security-groups={{ DEP_CONFIGURATION_0_SPEC_PLATFORM_0_SPEC_SECGROUPCOUNT | default("1") }}
security-group-rules={{ DEP_CONFIGURATION_0_SPEC_PLATFORM_0_SPEC_SECGROUPRULECOUNT | default("16") }}
volumes={{ DEP_CONFIGURATION_0_SPEC_PLATFORM_0_SPEC_VOLUMECOUNT | default("0") }}
